on:
  workflow_call:
    inputs:
      before-command:
        description: Install command before `bundle install`
        type: string
        required: false
        default: ""
      bundle-without:
        description: Passed to `BUNDLE_WITHOUT` env
        type: string
        required: false
        default: ""
      ruby-version:
        description: Passed to `ruby/setup-ruby`
        type: string
        required: false
        default: ruby

    secrets:
      slack-webhook:
        description: Slack incoming webhook url
        required: false

jobs:
  pages-yard:
    name: Deploy yard to Pages

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Allow one concurrent deployment
    concurrency:
      group: pages
      cancel-in-progress: true

    runs-on: ubuntu-latest

    env:
      BUNDLE_WITHOUT: ${{ inputs.bundle-without }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Prepare for bundle install
        run: ${{ inputs.before-command }}
        if: inputs.before-command != ''

      - uses: ruby/setup-ruby@8d27f39a5e7ad39aebbcbd1324f7af020229645c # v1.287.0
        with:
          ruby-version: ${{ inputs.ruby-version }}
          bundler-cache: true

      - name: Generate yard
        run: bundle exec yard --output-dir "${DOC_DIR}"
        env:
          DOC_DIR: ${{ runner.temp }}/doc

      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          # Upload entire repository
          path: ${{ runner.temp }}/doc

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5

      - name: Slack Notification (not success)
        uses: act10ns/slack@cfcc30955fe9377f4f55e1079e5419ee1014269f # v2
        if: "! success()"
        continue-on-error: true
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.slack-webhook }}
