# Run `rbs collection update` and create Pull Request for rbs_collection.lock.yaml

on:
  workflow_call:
    inputs:
      assignees:
        description: PR assignees
        type: string
        required: false
      auto-merge:
        description: Whether set auto-marge to created PR
        type: boolean
        required: false
        default: false
      ruby-version:
        description: Passed to `ruby/setup-ruby`
        type: string
        required: false
        default: ruby

    secrets:
      app-id:
        description: GitHub App ID
        required: true
      private-key:
        description: GitHub App private key
        required: true
      slack-webhook:
        description: Slack incoming webhook url
        required: false

jobs:
  rbs-collection-updater:
    name: Update rbs_collection.lock.yaml

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: ruby/setup-ruby@708024e6c902387ab41de36e1669e43b5ee7085e # v1.283.0
        with:
          ruby-version: ${{ inputs.ruby-version }}
          bundler-cache: true

      - run: bundle exec rbs collection update

      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ secrets.app-id }}
          private-key: ${{ secrets.private-key }}
          permission-contents: write
          permission-pull-requests: write

      - uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        id: cpr
        with:
          token: ${{ steps.app-token.outputs.token }}
          committer: GitHub <noreply@github.com>
          title: "Update rbs_collection.lock.yaml"
          commit-message: "Run `bundle exe rbs collection update`"
          labels: rbs-collection-updater
          branch: rbs-collection-updater
          branch-suffix: short-commit-hash
          assignees: ${{ inputs.assignees }}
          add-paths: |
            rbs_collection.lock.yaml

      - name: Enable auto-merge
        if: inputs.auto-merge && steps.cpr.outputs.pull-request-url
        run: |
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ steps.cpr.outputs.pull-request-url }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Slack Notification (not success)
        uses: act10ns/slack@cfcc30955fe9377f4f55e1079e5419ee1014269f # v2
        if: "! success()"
        continue-on-error: true
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.slack-webhook }}
